Repository 2019-2020-ps6/2022-2023-ps6-webonjour, pull requests merged in 2023-05, with the labels that each got.

#184 157 fix quiz creation
  apps/front-end/back-office/src/app/app.module.ts
  apps/front-end/back-office/src/app/app.routes.ts
  apps/front-end/back-office/src/app/components/dashboard/quiz/quiz-list/quiz-list.component.ts
  apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.html
  apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.scss
  apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.spec.ts
  apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.ts
  apps/front-end/back-office/src/app/components/util/file-field/file-field.component.html
  apps/front-end/back-office/src/app/components/util/file-field/file-field.component.scss
  apps/front-end/back-office/src/app/components/util/file-field/file-field.component.spec.ts
  apps/front-end/back-office/src/app/components/util/file-field/file-field.component.ts
  libs/data-access-fake-backend/src/lib/interceptors/fake-backend.interceptor.ts
Labels: fix

#191 fix: picture preview in patient
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.spec.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.ts
  apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.spec.ts
  apps/front-end/back-office/src/app/components/util/file-field/file-field.component.ts
Labels: fix

#207 206 add floor to patient
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-list/patient-list.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-list/patient-list.component.ts
  libs/data-access-fake-backend/src/lib/mocks/patient.ts
  libs/util-interface/src/lib/patient/index.ts
Labels: feature

#204 fix: add message when no quiz to add
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz-add-popup/patient-edit-quiz-add-popup.component.html
Labels: feature

#194 192 add scroll to family member edit and fix family profile picture
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-family-add-popup/patient-family-add-popup.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-family-add-popup/patient-family-add-popup.component.spec.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-family-add-popup/patient-family-add-popup.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-family/patient-family.component.html
Labels: fix

#198 180 learning card
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-answers/question-detail-answers.component.spec.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-clues/question-detail-clues.component.spec.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-main/question-detail-main.component.spec.ts
  apps/front-end/back-office/src/app/components/quiz-edition/quiz-edition.component.ts
  apps/front-end/front-office/src/app/app.module.ts
  apps/front-end/front-office/src/app/app.routes.ts
  apps/front-end/front-office/src/app/components/drag-and-drop/drag-and-drop.component.ts
  apps/front-end/front-office/src/app/components/learning/choice/choice.component.html
  apps/front-end/front-office/src/app/components/learning/choice/choice.component.scss
  apps/front-end/front-office/src/app/components/learning/choice/choice.component.ts
  apps/front-end/front-office/src/app/components/learning/learning.component.html
  apps/front-end/front-office/src/app/components/learning/learning.component.scss
  apps/front-end/front-office/src/app/components/learning/learning.component.ts
  apps/front-end/front-office/src/app/components/learning/order/order.component.html
  apps/front-end/front-office/src/app/components/learning/order/order.component.scss
  apps/front-end/front-office/src/app/components/learning/order/order.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/game-answer/game-answer.component.html
  apps/front-end/front-office/src/app/components/quiz-view/game-answer/game-answer.component.scss
  apps/front-end/front-office/src/app/components/quiz-view/game-answer/game-answer.component.spec.ts
  apps/front-end/front-office/src/app/components/quiz-view/game-answer/game-answer.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.html
  apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.scss
  apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-header/help-page-header.component.html
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-header/help-page-header.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/skip-button/skip-button.component.ts
  apps/front-end/front-office/src/app/components/quiz/quiz-list-item/quiz-list-item.component.ts
  apps/front-end/front-office/src/app/reducers/game/game.actions.ts
  apps/front-end/front-office/src/app/reducers/game/game.effects.spec.ts
  apps/front-end/front-office/src/app/reducers/game/game.effects.ts
  apps/front-end/front-office/src/app/reducers/game/game.models.ts
  apps/front-end/front-office/src/app/reducers/game/game.reducer.spec.ts
  apps/front-end/front-office/src/app/reducers/game/game.reducer.ts
  apps/front-end/front-office/src/app/reducers/game/game.selectors.spec.ts
  apps/front-end/front-office/src/app/reducers/game/game.selectors.ts
  apps/front-end/front-office/src/styles.scss
  libs/data-access-fake-backend/src/lib/mocks/patient.ts
  libs/data-access-fake-backend/src/lib/mocks/quiz.ts
  libs/util-interface/src/lib/quiz/index.ts
Labels: feature

#202 feat: add danger zone
  apps/front-end/back-office/src/app/app.module.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.scss
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.spec.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit/patient-edit.component.html
Labels: feature

#211 199 betterify css
  apps/front-end/front-office/src/app/app.component.scss
  apps/front-end/front-office/src/app/app.module.ts
  apps/front-end/front-office/src/app/components/header/header.component.html
  apps/front-end/front-office/src/app/components/header/header.component.scss
  apps/front-end/front-office/src/app/components/homepage/card-container/card-container.component.html
  apps/front-end/front-office/src/app/components/homepage/card/card.component.html
  apps/front-end/front-office/src/app/components/homepage/card/card.component.scss
  apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.html
  apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.scss
  apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-header/help-page-header.component.html
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-header/help-page-header.component.scss
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-header/help-page-header.component.spec.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-header/help-page-header.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-hint/help-page-hint.component.html
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-hint/help-page-hint.component.scss
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-hint/help-page-hint.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-return/help-page-return.component.html
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-return/help-page-return.component.scss
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-return/help-page-return.component.spec.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page-return/help-page-return.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.html
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.scss
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.spec.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/message/message.component.html
  apps/front-end/front-office/src/app/components/quiz-view/quiz-results/quiz-results.component.html
  apps/front-end/front-office/src/app/components/quiz-view/quiz-results/quiz-results.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/skip-button/skip-button.component.html
  apps/front-end/front-office/src/app/components/quiz-view/skip-button/skip-button.component.scss
  apps/front-end/front-office/src/app/components/quiz-view/skip-button/skip-button.component.spec.ts
  apps/front-end/front-office/src/app/components/quiz-view/skip-button/skip-button.component.ts
  apps/front-end/front-office/src/app/components/quiz/quiz-item/quiz-item.component.scss
  apps/front-end/front-office/src/app/components/quiz/quiz-list-item/quiz-list-item.component.scss
  apps/front-end/front-office/src/styles.scss
Labels: enhancement, feature

#222 feat: more data to charts
  apps/front-end/back-office/project.json
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-stats/patient-edit-stats.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-stats/patient-edit-stats.component.ts
Labels: feature

#224 fix: type
  apps/front-end/front-office/src/app/components/quiz/quiz-item/quiz-item.component.ts
Labels: fix

#226 feat: css shenanigans
  apps/front-end/front-office/src/app/components/drag-and-drop/drag-and-drop.component.html
  apps/front-end/front-office/src/app/components/drag-and-drop/drag-and-drop.component.scss
  apps/front-end/front-office/src/app/components/drag-and-drop/drag-and-drop.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.scss
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.html
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.ts
Labels: feature

#227 feat: fuck relative imports
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.ts
Labels: fix

#230 feat: floor selection
  apps/front-end/front-office/src/app/components/homepage/card-container/card-container.component.html
  apps/front-end/front-office/src/app/components/homepage/card-container/card-container.component.ts
Labels: feature

#233 232 merge dev in 162
  apps/backend/api/controllers/.gitkeep
  apps/backend/api/middleware/.gitkeep
  apps/backend/api/middleware/validate.ts
  apps/backend/api/project.json
  apps/backend/api/routes/.gitkeep
  apps/backend/api/schemas/.gitkeep
  apps/backend/api/services/.gitkeep
  apps/backend/backend-api-e2e/project.json
  apps/front-end/back-office/src/app/app.module.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz-add-popup/patient-edit-quiz-add-popup.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz/patient-edit-quiz.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz/patient-edit-quiz.component.ts
  libs/data-access-fake-backend/src/lib/interceptors/fake-backend.interceptor.ts
  package-lock.json
  package.json
Labels: fix

#247 238 fix everything
  apps/backend/api/src/main.ts
  apps/front-end/back-office/src/app/components/dashboard/dashboard-header/dashboard-header.component.scss
  apps/front-end/back-office/src/app/components/dashboard/dashboard-header/dashboard-header.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-create/patient-create.component.scss
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-create/patient-create.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.scss
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-accommodation/patient-edit-accommodation.component.scss
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-accommodation/patient-edit-accommodation.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.scss
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz-add-popup/patient-edit-quiz-add-popup.component.scss
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz-add-popup/patient-edit-quiz-add-popup.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-stats/patient-edit-stats.component.scss
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-stats/patient-edit-stats.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit/patient-edit.component.scss
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit/patient-edit.component.ts
  apps/front-end/back-office/src/app/components/dashboard/side-nav/profile/profile.component.scss
  apps/front-end/back-office/src/app/components/dashboard/side-nav/profile/profile.component.ts
  apps/front-end/back-office/src/app/components/util/file-field/file-field.component.scss
  apps/front-end/back-office/src/app/components/util/file-field/file-field.component.ts
  apps/front-end/front-office/src/app/app.component.scss
  apps/front-end/front-office/src/app/app.component.ts
  apps/front-end/front-office/src/app/components/drag-and-drop/drag-and-drop.component.ts
  apps/front-end/front-office/src/app/components/learning/choice/choice.component.scss
  apps/front-end/front-office/src/app/components/learning/choice/choice.component.ts
  apps/front-end/front-office/src/app/components/learning/learning.component.scss
  apps/front-end/front-office/src/app/components/learning/learning.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-popup/help-popup.component.html
  apps/front-end/front-office/src/app/components/quiz-view/help-popup/help-popup.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/quiz-results/quiz-results.component.ts
  libs/util-interface/src/lib/auth/index.ts
  libs/util-interface/src/lib/tts/index.ts
Labels: fix

#249 feat: add postgres to prisma
  .env
  apps/backend/api/docker-compose.yml
  apps/backend/backend-api-e2e/src/support/global-setup.ts
  apps/backend/backend-api-e2e/src/support/global-teardown.ts
  docker-compose.yml
  prisma/migrations/20230515065227_init/migration.sql
  prisma/migrations/20230515091821_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: feature

#242 239 create prisma models for patient
  apps/util-scripts/src/main.ts
  libs/data-access-mocks/src/lib/mocks/auth.ts
  prisma/migrations/20230518165052_add_patient/migration.sql
  prisma/migrations/20230518170427_fix_user_id/migration.sql
  prisma/migrations/20230518170836_add_picture_to_user/migration.sql
  prisma/schema.prisma
Labels: feature

#251 250 fix docker pipeline
  .dockerignore
  .gitignore
  apps/backend/api/Dockerfile
  apps/backend/api/assets/.gitkeep
  apps/backend/api/package.json
  apps/backend/api/project.json
  apps/backend/api/src/env.config.loader.ts
  apps/front-end/back-office/project.json
  apps/front-end/front-office/project.json
  docker-compose-full.yml
  package-lock.json
  prisma/schema.prisma
Labels: fix

#254 refactor: use prisma types front-end-front-office
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz-add-popup/patient-edit-quiz-add-popup.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz/patient-edit-quiz.component.ts
  apps/front-end/back-office/src/app/components/dashboard/quiz/quiz-list/quiz-list.component.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-answer/question-detail-answer.component.spec.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-answer/question-detail-answer.component.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-answers/question-detail-answers.component.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-clue/question-detail-clue.component.spec.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-clue/question-detail-clue.component.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-clues/question-detail-clues.component.spec.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-clues/question-detail-clues.component.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-main/question-detail-main.component.spec.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail-main/question-detail-main.component.ts
  apps/front-end/back-office/src/app/components/quiz-creation/question-detail/question-detail.component.ts
  apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.ts
  apps/front-end/back-office/src/app/components/quiz-edition/quiz-edition.component.ts
  apps/front-end/front-office/src/app/components/drag-and-drop/drag-and-drop.component.ts
  apps/front-end/front-office/src/app/components/learning/choice/choice.component.ts
  apps/front-end/front-office/src/app/components/learning/learning.component.ts
  apps/front-end/front-office/src/app/components/learning/order/order.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-page/help-page.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/help-popup/help-popup.component.ts
  apps/front-end/front-office/src/app/reducers/game/game.actions.ts
  apps/front-end/front-office/src/app/reducers/game/game.effects.ts
  apps/front-end/front-office/src/app/reducers/game/game.models.ts
  apps/front-end/front-office/src/app/reducers/game/game.reducer.spec.ts
  apps/front-end/front-office/src/app/reducers/game/game.reducer.ts
  apps/util-scripts/src/main.ts
  libs/data-access-fake-backend/src/lib/interceptors/fake-backend.interceptor.ts
  libs/data-access-mocks/src/lib/mocks/patient.ts
  libs/data-access-mocks/src/lib/mocks/quiz.ts
  libs/front-end/shared/common/src/lib/services/patient/patient.service.ts
  libs/front-end/shared/common/src/lib/services/quiz/quiz.service.ts
  libs/util-interface/src/lib/patient/index.ts
  libs/util-interface/src/lib/quiz/index.ts
  package-lock.json
  package.json
Labels: refactor

#266 Hotfix docker build
  apps/front-end/back-office/project.json
  apps/front-end/front-office/project.json
Labels: ci, fix

#262 260 make basic crud for patients
  .gitignore
  apps/backend/api/src/controllers/patient.accommodation.controller.ts
  apps/backend/api/src/controllers/patient.controller.ts
  apps/backend/api/src/controllers/patient.family-member.controller.ts
  apps/backend/api/src/controllers/patient.quiz.controller.ts
  apps/backend/api/src/controllers/quiz.controller.ts
  apps/backend/api/src/main.ts
  apps/backend/api/src/middleware/requestPreParsers.ts
  apps/backend/api/src/middleware/validate.ts
  apps/backend/api/src/routes/patient.route.ts
  apps/backend/api/src/routes/quiz.route.ts
  apps/backend/api/tsconfig.json
  apps/front-end/back-office/project.json
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-danger/patient-danger.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-accommodation/patient-edit-accommodation.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz-add-popup/patient-edit-quiz-add-popup.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-family-add-popup/patient-family-add-popup.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-family/patient-family.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-list/patient-list.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-list/patient-list.component.ts
  apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.spec.ts
  apps/front-end/back-office/src/app/components/quiz-creation/quiz-create/quiz-create.component.ts
  apps/front-end/front-office/project.json
  apps/front-end/front-office/src/app/components/homepage/card-container/card-container.component.ts
  apps/front-end/front-office/src/app/components/homepage/card/card.component.spec.ts
  apps/front-end/front-office/src/app/components/homepage/card/card.component.ts
  apps/front-end/front-office/src/app/components/quiz-view/game-question/game-question.component.ts
  apps/front-end/front-office/src/app/reducers/game/game.actions.ts
  apps/front-end/front-office/src/app/reducers/game/game.effects.spec.ts
  apps/front-end/front-office/src/app/reducers/game/game.models.ts
  apps/front-end/front-office/src/app/reducers/game/game.reducer.spec.ts
  apps/util-scripts/src/main.ts
  apps/util-scripts/tsconfig.json
  flake.nix
  libs/data-access-fake-backend/src/lib/interceptors/fake-backend.interceptor.ts
  libs/data-access-mocks/src/lib/mocks/patient.ts
  libs/front-end/shared/common/src/index.ts
  libs/front-end/shared/common/src/lib/services/family-member/family-member.service.spec.ts
  libs/front-end/shared/common/src/lib/services/family-member/family-member.service.ts
  libs/front-end/shared/common/src/lib/services/patient/patient.service.ts
  libs/util-interface/src/index.ts
  libs/util-interface/src/lib/patient/index.ts
  package-lock.json
  package.json
  prisma/migrations/20230523152325_fix_typo/migration.sql
  prisma/migrations/20230525133614_remove_last_quiz_date/migration.sql
  prisma/schema.prisma
Labels: feature

#272 fix: docker prisma generate
  .dockerignore
  apps/backend/api/Dockerfile
  apps/util-scripts/Dockerfile
  prisma/schema.prisma
Labels: ci, fix

#275 feat: add crud to family-member
  apps/backend/api/src/controllers/family-member.controller.ts
  apps/backend/api/src/main.ts
  apps/backend/api/src/routes/family-member.route.ts
Labels: feature

#273 252 feat make basic crud for quiz
  apps/backend/api/src/controllers/accommodation.controller.ts
  apps/backend/api/src/controllers/answer.controller.ts
  apps/backend/api/src/controllers/patient.accommodation.controller.ts
  apps/backend/api/src/controllers/quiz.controller.ts
  apps/backend/api/src/main.ts
  apps/backend/api/src/routes/accommodation.route.ts
  apps/backend/api/src/routes/answer.route.ts
  apps/backend/api/src/routes/quiz.route.ts
Labels: feature
