Repository 2019-2020-ps6/2022-2023-ps6-webonjour, pull requests merged in 2023-06, with the labels that each got.

#307 301 feat make auth jwt
  apps/backend/api/config/custom-environment-variables.json
  apps/backend/api/config/default.json
  apps/backend/api/package.json
  apps/backend/api/src/controllers/auth.controller.ts
  apps/backend/api/src/controllers/patient.quiz.controller.ts
  apps/backend/api/src/main.ts
  apps/backend/api/src/middleware/deserializeUser.ts
  apps/backend/api/src/routes/accommodation.route.ts
  apps/backend/api/src/routes/answer.route.ts
  apps/backend/api/src/routes/auth.route.ts
  apps/backend/api/src/routes/clue.route.ts
  apps/backend/api/src/routes/question.route.ts
  apps/backend/api/src/routes/quiz.route.ts
  apps/backend/api/src/utils/jwt.ts
  apps/backend/api/src/utils/password.ts
  apps/backend/backend-api-e2e/src/support/test-setup.ts
  apps/front-end/back-office/src/app/components/dashboard/side-nav/profile/profile.component.html
  apps/util-scripts/src/main.ts
  libs/data-access-fake-backend/src/lib/interceptors/fake-backend.interceptor.ts
  libs/util-interface/src/lib/auth/index.ts
  package-lock.json
  package.json
Labels: feature

#308 accommodations cannot be seen / edited
  apps/backend/api/src/controllers/patient.accommodation.controller.ts
  apps/backend/api/src/main.ts
  apps/backend/api/src/routes/patient.route.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-accommodation/patient-edit-accommodation.component.ts
  libs/front-end/shared/common/src/lib/services/patient/patient.service.ts
Labels: fix

#312 311 cannot add patient family the family member is created but not connected to the patient the api is not even called
  apps/backend/api/src/routes/patient.route.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz/patient-edit-quiz.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-quiz/patient-edit-quiz.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-family-add-popup/patient-family-add-popup.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-family/patient-family.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-family/patient-family.component.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-list/patient-list.component.html
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-list/patient-list.component.ts
  apps/front-end/back-office/src/app/components/dashboard/quiz/quiz-list/quiz-list.component.html
  apps/front-end/back-office/src/app/components/dashboard/quiz/quiz-list/quiz-list.component.ts
  apps/front-end/back-office/src/app/components/util/file-field/file-field.component.ts
  prisma/migrations/20230603121911_make_profilepicture_optional/migration.sql
  prisma/migrations/20230603125935_make_image_url_quiz_optional/migration.sql
  prisma/schema.prisma
Labels: fix

#317 feat: add util
  apps/backend/api/src/main.ts
  apps/front-end/back-office/src/app/components/dashboard/patient/patient-edit/patient-edit-general/patient-edit-general.component.ts
  libs/front-end/shared/common/src/index.ts
  libs/front-end/shared/common/src/lib/utils/fileToBase64.ts
Labels: feature

#279 feat: add environement
  apps/backend/api/project.json
  apps/backend/api/src/main.ts
  apps/backend/backend-api-e2e/src/support/test-setup.ts
  apps/front-end/back-office/project.json
  apps/front-end/back-office/src/app/services/auth/auth.service.ts
  apps/front-end/front-office/project.json
  apps/front-end/front-office/src/app/components/header/header.component.html
  apps/front-end/front-office/src/app/components/header/header.component.ts
  libs/front-end/shared/common/src/lib/services/family-member/family-member.service.ts
  libs/front-end/shared/common/src/lib/services/patient/patient.service.ts
  libs/front-end/shared/common/src/lib/services/question/question.service.ts
  libs/front-end/shared/common/src/lib/services/quiz/quiz.service.ts
  libs/front-end/shared/common/src/lib/services/tts/tts.service.ts
  libs/shared/environments/.babelrc
  libs/shared/environments/.eslintrc.json
  libs/shared/environments/README.md
  libs/shared/environments/jest.config.ts
  libs/shared/environments/project.json
  libs/shared/environments/src/index.ts
  libs/shared/environments/src/lib/environment.prod.ts
  libs/shared/environments/src/lib/environment.ts
  libs/shared/environments/tsconfig.json
  libs/shared/environments/tsconfig.lib.json
  libs/shared/environments/tsconfig.spec.json
  tsconfig.base.json
Labels: feature

#334 fix: missing packages
  apps/backend/api/package.json
Labels: fix

#346 fix: api routes
  apps/front-end/back-office/project.json
  apps/front-end/back-office/src/app/services/auth/auth.service.ts
  libs/front-end/shared/common/src/lib/services/family-member/family-member.service.ts
  libs/front-end/shared/common/src/lib/services/patient/patient.service.ts
  libs/front-end/shared/common/src/lib/services/question-result/question-result.service.ts
  libs/front-end/shared/common/src/lib/services/question/question.service.ts
  libs/front-end/shared/common/src/lib/services/quiz-session/quiz-session.service.ts
  libs/front-end/shared/common/src/lib/services/quiz/quiz.service.ts
  libs/front-end/shared/common/src/lib/services/tts/tts.service.ts
  libs/shared/environments/src/index.ts
Labels: fix

#372 feat: test quiz add/delete
  apps/front-end/back-office-e2e/src/assets/images/quiz_image.png
  apps/front-end/back-office-e2e/src/fixtures.ts
  apps/front-end/back-office-e2e/src/menu/menu.fixture.ts
  apps/front-end/back-office-e2e/src/menu/menu.spec.ts
  apps/front-end/back-office-e2e/src/quiz/quiz.add.fixture.ts
  apps/front-end/back-office-e2e/src/quiz/quiz.edit.fixture.ts
  apps/front-end/back-office-e2e/src/quiz/quiz.fixture.ts
  apps/front-end/back-office-e2e/src/quiz/quiz.spec.ts
Labels: tests

#375 fix: let db choose id
  apps/util-scripts/src/main.ts
Labels: fix

#379 365 front office tests
  apps/backend/backend-api-e2e/src/support/global-setup.ts
  apps/backend/backend-api-e2e/src/support/global-teardown.ts
  apps/front-end/back-office-e2e/playwright.config.ts
  apps/front-end/back-office-e2e/src/support/global-setup.ts
  apps/front-end/back-office-e2e/src/support/global-teardown.ts
  apps/front-end/back-office/project.json
  apps/front-end/front-office-e2e/project.json
  apps/front-end/front-office-e2e/src/app.spec.ts
  apps/front-end/front-office-e2e/src/fixture.ts
  apps/front-end/front-office-e2e/src/floor-selection/floor-selection.fixture.ts
  apps/front-end/front-office-e2e/src/floor-selection/floor-selection.spec.ts
  apps/front-end/front-office-e2e/src/header/header.spec.ts
  apps/front-end/front-office-e2e/src/help-page/help-page.fixture.ts
  apps/front-end/front-office-e2e/src/help-page/help-page.spec.ts
  apps/front-end/front-office-e2e/src/learning-card-selection/learning-card-selection.fixture.ts
  apps/front-end/front-office-e2e/src/learning-card-selection/learning-card-selection.spec.ts
  apps/front-end/front-office-e2e/src/patient-selection/patient-selection.fixture.ts
  apps/front-end/front-office-e2e/src/patient-selection/patient-selection.spec.ts
  apps/front-end/front-office-e2e/src/question/question.fixture.ts
  apps/front-end/front-office-e2e/src/question/question.spec.ts
  apps/front-end/front-office-e2e/src/quiz-selection/quiz-selection.fixture.ts
  apps/front-end/front-office-e2e/src/quiz-selection/quiz-selection.spec.ts
  apps/front-end/front-office-e2e/src/results-selection/result-selection.fixture.ts
  apps/front-end/front-office-e2e/src/results-selection/result-selection.spec.ts
  apps/front-end/front-office-e2e/src/simple-question/simple-question.fixture.ts
  apps/front-end/front-office-e2e/src/support/global-setup.ts
  apps/front-end/front-office-e2e/src/support/global-teardown.ts
  apps/front-end/front-office/project.json
  apps/front-end/front-office/src/app/components/header/header.component.html
  apps/front-end/front-office/src/app/components/header/header.component.ts
  libs/shared/environments/src/lib/environment.prod.ts
  package-lock.json
  playwright.config.base.ts
Labels: tests

#382 380 add trans office tests
  apps/front-end/back-office-e2e/src/login/login.spec.ts
  apps/front-end/back-office-e2e/src/menu/menu.spec.ts
  apps/front-end/back-office-e2e/src/patient/patient.spec.ts
  apps/front-end/back-office-e2e/src/quiz/quiz.spec.ts
  apps/front-end/front-office-e2e/src/floor-selection/floor-selection.spec.ts
  apps/front-end/front-office-e2e/src/header/header.spec.ts
  apps/front-end/front-office-e2e/src/help-page/help-page.spec.ts
  apps/front-end/front-office-e2e/src/learning-card-selection/learning-card-selection.spec.ts
  apps/front-end/front-office-e2e/src/patient-selection/patient-selection.spec.ts
  apps/front-end/front-office-e2e/src/question/question.spec.ts
  apps/front-end/front-office-e2e/src/quiz-selection/quiz-selection.spec.ts
  apps/front-end/front-office-e2e/src/results-selection/result-selection.spec.ts
  libs/fixtures-e2e/.babelrc
  libs/fixtures-e2e/.eslintrc.json
  libs/fixtures-e2e/README.md
  libs/fixtures-e2e/jest.config.ts
  libs/fixtures-e2e/project.json
  libs/fixtures-e2e/src/index.ts
  libs/fixtures-e2e/src/lib/back-office/fixtures.ts
  libs/fixtures-e2e/src/lib/back-office/login/login.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/menu/menu.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/patient/patient.add.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/patient/patient.edit.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/patient/patient.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/quiz/answer.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/quiz/clue.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/quiz/question.add.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/quiz/question.edit.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/quiz/quiz.add.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/quiz/quiz.edit.fixture.ts
  libs/fixtures-e2e/src/lib/back-office/quiz/quiz.fixture.ts
  libs/fixtures-e2e/src/lib/front-office/fixture.ts
  libs/fixtures-e2e/src/lib/front-office/floor-selection/floor-selection.fixture.ts
  libs/fixtures-e2e/src/lib/front-office/help-page/help-page.fixture.ts
  libs/fixtures-e2e/src/lib/front-office/learning-card-selection/learning-card-selection.fixture.ts
  libs/fixtures-e2e/src/lib/front-office/patient-selection/patient-selection.fixture.ts
  libs/fixtures-e2e/src/lib/front-office/question/question.fixture.ts
  libs/fixtures-e2e/src/lib/front-office/quiz-selection/quiz-selection.fixture.ts
  libs/fixtures-e2e/src/lib/front-office/results-selection/result-selection.fixture.ts
  libs/fixtures-e2e/src/lib/front-office/simple-question/simple-question.fixture.ts
  libs/fixtures-e2e/tsconfig.json
  libs/fixtures-e2e/tsconfig.lib.json
  libs/fixtures-e2e/tsconfig.spec.json
  playwright.config.base.ts
  tsconfig.base.json
Labels: tests
